example/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("redisapp.urls"))
]

redisapp/urls.py
from django.urls import path
from .views import HomeView, DetailView

app_name = "redisapp"

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('detail/<int:id>', DetailView.as_view(), name="detail")
]

redisapp/models.py
from django.db import models

# Create your models here.

redisapp/views.py
import requests
from django.shortcuts import render
from django.core.cache import cache
from django.views.generic import View


class HomeView(View):
    def get(self, request, *args, **kwargs):
        posts = requests.get("https://jsonplaceholder.typicode.com/posts")
        context = {
            "posts": posts.json()
        }
        return render(request,'home.html', context) 


class DetailView(View):
    def get(self, request, *args, **kwargs):
        post_id = kwargs.get("id")
        cache_item = cache.get(f"posts:{post_id}")
        if cache_item:
            detail = cache_item
            detail['from'] = "data from redis cache"
        else:
            detail = post_item = requests.get(f"https://jsonplaceholder.typicode.com/posts/{post_id}").json()
            detail['from'] = f"""
                                data from jsonplaceholder <br> refresh this page <br> or <br> click this link
                                 <a href="http://localhost:8000/detail/{post_id}">to redis cache</a>
                                """
            cache.set(f"posts:{post_id}", detail)
        context = {
            "post":detail
        }
        return render(request, "detail.html", context)
        

redisapp/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        {{post.title}}
    </h1>
    <h3>
        {{post.body}}
    </h3>
    <p style="color:red;">
        <b>
            {{post.from|safe}}
        </b>
    </p>
    <style>
        *{
            font-family: Tahoma;
            text-align: center;
        }
    </style>
</body>
</html>

redisapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redia app</title>
</head>
<body>
    <h1 style="text-align:center;">
        Click ...more link 
    </h1>
    <ul>
        {% for post in posts %} 
             <li>
                <h2>{{post.title}}</h2>
                <p>
                    {{post.body|slice:"0:100"}}
                    <a href="{% url 'redisapp:detail' post.id %}">...more</a>
                </p>
             </li>
        {% endfor %}
    </ul>
    <style>
        *{
            font-family: Tahoma;
        }
        ul{
            padding: 0px 5%;
        }
        ul li{
            border:1px solid black;
            list-style-type: none;
            border-radius: 10px;
            margin-bottom: 10px;
            padding: 0px 5%;
        }
    </style>
</body>
</html>